apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: first-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://pluhin.github.io/helm-36-26/
    targetRevision: 0.1.0
    chart: first-app
    helm:
      parameters:
        - name: istio.hosts[0]
          value: app-helm.k8s-9.sa
        - name: istio.hosts[1]
          value: app-helm.k8s-10.sa
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
